# Generated by Django 4.1.6 on 2023-02-22 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "Cat_name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Cat_info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ClassNames",
            fields=[
                (
                    "classnames",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("email", models.TextField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=50)),
                ("rdate", models.DateTimeField()),
                ("dept", models.CharField(max_length=10)),
                ("fire", models.CharField(max_length=2)),
                (
                    "classname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YourClass.classnames",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("Post_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("file", models.TextField()),
                ("date", models.DateTimeField()),
                ("viewcount", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YourClass.categories",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YourClass.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("Comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "Post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="YourClass.post"
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="YourClass.member",
                    ),
                ),
            ],
        ),
    ]
