# Generated by Django 4.1.7 on 2023-02-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("YourClass", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="viewcount",
            field=models.TextField(default=0),
        ),
    ]
