# Generated by Django 4.1.6 on 2023-02-24 12:15

import YourClass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("YourClass", "0003_alter_post_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="filename",
            field=models.CharField(max_length=64, null=True, verbose_name="첨부파일명"),
        ),
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=YourClass.models.get_file_path,
                verbose_name="파일",
            ),
        ),
    ]
